### ISSUE TITLE
Erreurs de configuration détectées

### ISSUE THREAD

**Issue by cinaxx** [ryann72/Home-assistant-tutoriel#1]
Bonjour Yann 
Je voulais dans un premier temps te remercier pour ce tuto mais j'ai un petit probléme 
Lorsque j'arrive ici "Affichage et configuration dans lovelace" je crée donc ma carte manuel mais celle ci a une erreur et donc impossible d'enregistrer. J'ai checké l'ensemble du tuto avant et je ne pense pas avoir fait de connerie.
Mes infos
Manuel Card :

type: 'custom:xiaomi-vacuum-map-card'
entity: vacuum.xiaomi_vacuum_cleaner #nom de ton entité aspirateur « vacuum.xxxx »
map_camera: camera.aspirateur  #nom de ton entité caméra vu juste avant…
camera_calibration: true  #permet de récupérer la calibration automatique
language: fr #langue de la carte
modes:
	- predefined_zones
	- go_to_target
	- zoned_cleanup
zones:
	- - - 18689
		- 23007
		- 26285
		- 28692
	- - - 26058 #Chambre
		- 24371
		- 29424
		- 28647
	- - - 26467 #Chambre enfants
		- 17367
		- 29424
		- 21779
	- - - 26103 #Couloir Chambres
		- 21551
		- 27241
		- 25235
	- - - 24330 #Couloir entrée
		- 21597
		- 26786
		- 22779
	- - - 27195 #Salle de Bain
		- 22324
		- 28560
		- 24553
	- - - 22328 #Entrée
		- 21278
		- 24784
		- 24189
	- - - 22010 #Entrée
		- 19777
		- 23693
		- 21779
	- - - 23192 #Entrée
		- 17276
		- 25967
		- 21551

Message d'erreur 
Erreurs de configuration détectées:
end of the stream or a document separator is expected at line 8, column 2:
    	- go_to_target
     ^

Sachant que si je garde que ca j'ai bien ma map
type: 'custom:xiaomi-vacuum-map-card'
entity: vacuum.xiaomi_vacuum_cleaner
map_camera: camera.aspirateur 
camera_calibration: true  
language: fr #langue de la carte

Merci pour ton aide.

**Comment by ryann72** [comment]
Bonjour,


As tu bien respecté l'indentation tel que ci-dessous. 

`type: 'custom:xiaomi-vacuum-map-card'
entity: vacuum.xiaomi_vacuum_cleaner
map_camera: camera.aspirateur
camera_calibration: true
language: fr
modes:
  - predefined_zones
  - go_to_target
  - zoned_cleanup
zones:
  - - - 26050
      - 23600
      - 27050
      - 25300
  - - - 22300
      - 23200
      - 26050
      - 26250
  - - - 22300
      - 19600
      - 26050
      - 23450
  - - - 25400
      - 24700
      - 27050
      - 26250
  - - - 26050
      - 19600
      - 30550
      - 23750
`
Le code est la a également 
https://pastebin.com/Eb4vLimp

**Comment by cinaxx** [comment]
C'est ok il a du avoir un espace en place qq part alors que j'ai bien fait le copier coller ...
en revanche je suis confronté à un autre pb dois je ouvrir un autre ticket ou je peux le faire directement ici ? 
Si c'est le cas voici ma nouvelle problématique 
Ma version de HA : core-2021.3.4

Dans la partie "Automation ou script pour nettoyage par pièce ou zone." 
Cette commande ne fonctionne pas 
entity_id: vacuum.xiaomi_vacuum_cleaner
command: app_segment_clean
params:
	- 23

J'ai donc essayé de le mettre en mode UI ce qui correspond à 
service: vacuum.send_command
data:
  command: app_segment_clean
  params: -23
target:
  entity_id: vacuum.xiaomi_vacuum_cleaner

et j'ai comme retour 
"Unable to send command to the vacuum: {'code': -10000, 'message': 'data for segment is invalid'}"

Merci une nouvelle fois de ton aide

**Comment by ryann72** [comment]
Super si tu as réussi. 
Pour ton second problème, es tu sur que la room 23 existe ? 

Tu dois pouvoir trouver les room existants avec les outils de développement. 

Sinon tu peux le faire par zone 
service: xiaomi_miio.vacuum_clean_zone 
data: 
  zone: #coordonnées de la zone tel qu’insérées dans la carte 
	- - 27333 
	  - 28810 
	  - 28777 
	  - 33623 
repeats: 2 #nombre de répétition souhaité 
entity_id: vacuum.xiaomi_vacuum_cleaner

**Comment by ryann72** [comment]
J'imagine que le problème est résolu avec la solution ci-dessus je clos le sujet.
